### ISSUE TITLE
TRABAJO PRACTICO | Elegir Tema Prevención de Ataques de Presentación

### ISSUE THREAD

**Issue by PabloAsensio** [pasensio97/MUVA-biometria#1]
Tema a elegir entre (uno o varios):
- Imagen impresa en alta resolución
- Máscara realizada con papel impreso
- Máscara realizada con papel impreso con los ojos recortados
- Ataque mediante la utilización de un video en una Tablet
- Máscara 3D rígida (para un número limitado de individuos)

**Comment by PabloAsensio** [comment]
Yo elegiria el 1 y el 5

**Comment by SergioUcles** [comment]
También se puede basar en un tipo de sensor y explicar que tipos de ataques detecta. Lo digo por que en el caso del sensor térmico podría detectar los 4 primeros ataques (no se si el 5º también) y no haría falta recurrir a toda la base de datos, nos centraríamos en un tipo de imagen concreta.

**Comment by PabloAsensio** [comment]
Entiendo. Pero creo que deberíamos ver otra forma que cubra el 5 caso y ya de paso lo comparamos con el resto.
