### ISSUE TITLE
2 - Viola Jones

### ISSUE THREAD

**Issue by PabloAsensio** [pasensio97/MUVA-biometria#4]
Extraccion la region de la cara.

**Comment by SergioUcles** [comment]
Aquí paso dos enlaces de códigos de Viola-Jones.

En este el código, parece que todo esta bien. Enumera los pasos que realiza y como resultado encuadra la cara.
https://github.com/salvacarrion/viola-jones

En este otro indica como descargar la librería ViolaJones y deja el código explicado en un jupyter notebook.
https://github.com/Simon-Hohberg/Viola-Jones

**Comment by PabloAsensio** [comment]
Yo acabo de encontrar esto: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_objdetect/py_face_detection/py_face_detection.html

**Comment by PabloAsensio** [comment]
Parece que lo que ha subido @ruben1314 funciona correctamente. Cierro la Issue cuando @SergioUcles lo teste también.
