### ISSUE TITLE
7 - Clasificador por movimiento

### ISSUE THREAD

**Issue by PabloAsensio** [pasensio97/MUVA-biometria#7]

**Comment by SergioUcles** [comment]
El código esta subido en mi github, como detección de movimiento.

**Comment by PabloAsensio** [comment]
Subelo a esta repo en una branch. 
```git checkout -b nombre_branch```
para crear la branch en tu repo local

**Comment by PabloAsensio** [comment]
Así mismo te faltan sacar las métricas de la ISO. No se te olvide.
